### ISSUE TITLE
refresh the lockfile to automatically remove the vulnerability introduced by tree-kit

### ISSUE THREAD

**Issue by paimon0715** [hasura/graphqurl#101]
Hi, @wawhal, I have reported a [vulnerability issue](https://snyk.io/vuln/SNYK-JS-TREEKIT-1077068) in package **terminal-kit**.

As far as I am aware, vulnerability(high severity) [**SNYK-JS-TREEKIT-1077068**](https://snyk.io/vuln/SNYK-JS-TREEKIT-1077068) detected in package **tree-kit<0.7.0** is directly referenced by  **terminal-kit@1.49.3**, on which your package **graphqurl@1.0.1** directly depends. As such, this vulnerability can also affect **graphqurl@1.0.1** via the following path:
`graphqurl@1.0.1 ➔ terminal-kit@1.49.3 ➔ tree-kit@0.6.2(vulnerable version)`

Since **terminal-kit** has released a new patched version **terminal-kit@1.49.4** to resolve this issue (**terminal-kit@1.49.4 ➔ tree-kit@0.7.0(fix version)**), then this vulnerability patch can be automatically propagated into your project only if you **update your lockfile**. The following is your [**new dependency path**](https://npmgraph.js.org/?q=graphqurl%40+1.0.1) :
`graphqurl@1.0.1 ➔ terminal-kit@1.49.4 ➔ tree-kit@0.7.0(vulnerability fix version)`.

![dependency path](https://user-images.githubusercontent.com/86952306/130203517-8e48eef0-5d62-483f-8def-b530eded3e9d.png)

A warm tip.
Best regards,
^_^

**Comment by manasag** [comment]
Closing this as its probably resolved with recent npm upgrades.
