### ISSUE TITLE
Remove `package-lock.json` or update it to latest npm format

### ISSUE THREAD

**Issue by chtnnh** [hasura/graphqurl#103]
I am trying to fix #23 but I am unable to proceed as my attempts at installing `graphql-voyager` are hampered with [this](https://gist.github.com/chtnnh/893c74c8b0490a6e67a6dd5ba5a4c944) error.

**Comment by SwampDolphin97** [comment]
Isn't package.lock supposed to have the required versions of dependencies for running it?

**Comment by chtnnh** [comment]
Afaik, that information is stored in the package.json and not package.lock

**Comment by SwampDolphin97** [comment]
![image](https://user-images.githubusercontent.com/27912312/157054935-ab197708-be03-4f96-a8de-21837c831e87.png)

For locking the versions? I think they left it on purpose. I'm not able to build it either though lmao

**Comment by manasag** [comment]
Closing this as it doesn't apply anymore. The library is compliant with latest node and npm.
