### ISSUE TITLE
update graphql dependency to latest

### ISSUE THREAD

**Issue by FDiskas** [hasura/graphqurl#73]
Currently there is graphql": "0.9.1" installed as dependency - but Latest version: 15.3.0
Please update it - I gaving issue where exported schema includes wrong typings for example
```ql
type AppPurchaseOneTime implements AppPurchase, Node {
...
```
but this should be like
```ql
type AppPurchaseOneTime implements AppPurchase & Node {
...
```
http://spec.graphql.org/draft/#sec-Interfaces

So I'm hoping that updating the library will solve the issue.

**Comment by FDiskas** [comment]
Possible fix https://github.com/hasura/graphqurl/issues/73

**Comment by friend0** [comment]
@shahidhk I believe this is causing install issues
Peer dependencies are requesting higher versions of graphql

**Comment by ShraddhaAg** [comment]
closing this in favor of #111. @FDiskas thanks for reporting! 🙏
