### ISSUE TITLE
401 Unauthorized when connecting to GitHub HTTPS GraphQL API?

### ISSUE THREAD

**Issue by pzrq** [hasura/graphqurl#74]
I have a working [curl to access the GitHub API](https://docs.github.com/en/free-pro-team@latest/graphql/guides/introduction-to-graphql#discovering-the-graphql-api) (where `${TOKEN}` is a bash/zsh environment variable containing a valid GitHub [personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)):

```
curl -H "Authorization: bearer ${TOKEN}" https://api.github.com/graphql
```

However I can't seem get it to work with **graphqurl**?

```
$ gq https://api.github.com/graphql -H 'Authorization: bearer ${TOKEN}' 


Introspecting schema... !
    Error: Network error: Response not successful: Received status code 401
```

Wireshark shows it trying TLSv1.3 instead of TLSv1.2 though otherwise I'm unclear how to proceed without starting to dig into the source code here (and sadly don't have infinite time).

Aside: A demo in the animated GIFs works for me:

```
gq http://graphql.communitygraph.org/graphql/ -i
```

Edit: A nicer working curl:

```
 curl -H "Authorization: bearer ${TOKEN}" -X POST -d " \
 { \
   \"query\": \"query { viewer { login }}\" \
 } \
" https://api.github.com/graphql
{"data":{"viewer":{"login":"pzrq"}}}
```

Any ideas if I'm missing something obvious?

**Comment by robx** [comment]
> $ gq https://api.github.com/graphql -H 'Authorization: bearer ${TOKEN}' 

If this is literally what you typed, try using double quotes `"` around the `-H` argument instead of single quotes `'` to allow variable expansion.

**Comment by pzrq** [comment]
@robx Wonderful - thank you - that was it.
<img width="487" alt="Screen Shot 2020-11-27 at 9 31 11 pm" src="https://user-images.githubusercontent.com/1217010/100439664-eb706880-30f7-11eb-910f-156fa692c6ee.png">
