### ISSUE TITLE
Is a 1.0.0 release imminent?

### ISSUE THREAD

**Issue by OliverCole** [hasura/graphqurl#76]
#63 has some great stuff we really need (it upgrades some dependencies from versions with licensing challenges to versions without) - I also saw the version increased to 1.0.0.

I know it was only just merged, but is there a 1.0.0 release to npm coming soon? 

/cc @wawhal

**Comment by wawhal** [comment]
@OliverCole apologies for the delay in reply. It has been released. Do try out v1.0.1.
