### ISSUE TITLE
Isn't it need to Content-Type headers?

### ISSUE THREAD

**Issue by stardustrain** [hasura/graphqurl#97]
First, I appreciate made a good library for GraphQL environment.

I have a question in use graphqurl.

Isn't it need to `"Content-Type": "application/json"` headers when requests to GraphQL server?

I'd made a simple GraphQL server with fastify + mercurius, and using graphqurl in CLI but an error occurred this:
![image](https://user-images.githubusercontent.com/9318449/122355879-3adf8e80-cf8d-11eb-9acf-d2868c00ca5b.png)

I was found that `'content-type': 'text/plain;charset=UTF-8'` in request headers, therefore I think parsing body with inappropriate parsing logic when receiving request in fastify server.

I'm confused as to whether I need to modify the server's parsing logic for instance like this?
```js
fastify.addContentTypeParser('text/plain', { parseAs: 'string' }, function (req, body, done) {
  try {
    const json = JSON.parse(body)
    done(null, json)
  } catch (err) {
    err.statusCode = 400
    done(err, undefined)
  }
})
```
If this library is a problem and fixing it isn't a high priority, I'd like to try it.

**Comment by wawhal** [comment]
@stardustrain yes adding a `content-type` header would be useful as some graphql servers expect it. Feel free to open a pull request with the suggested change.

**Comment by stardustrain** [comment]
@wawhal #98 I was created pull request related to this issue. Thank you for your kindness.
